# Generated by Django 3.2.15 on 2022-09-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='testpres',
        ),
    ]
