# Generated by Django 3.2.16 on 2022-10-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0003_auto_20221002_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayonly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='did',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='labadmin.dayonly'),
        ),
    ]
