# Generated by Django 3.2.16 on 2022-10-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0004_auto_20221006_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labadmin.dayonly'),
        ),
    ]
