# Generated by Django 3.2.16 on 2022-10-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0005_alter_day_did'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
    ]
